name = "glowvm"
version = "0.1.0"
internal_modules = ["glowvm/internal", "glowvm/internal/*"]
description = "Run Gleam serverlessly via AtomVM compiled to WebAssembly"
licences = ["GPL-3.0-or-later", "Apache-2.0"]
repository = { type = "github", user = "withgiolt", repo = "glowvm" }
links = [{ title = "Docs", href = "https://docs.giolt.com/glowvm/about" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
orbital = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.7.0 and < 3.0.0"
gleam_package_interface = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 4.4.0 and < 5.0.0"
wisp = ">= 2.2.2 and < 3.0.0"
