name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.18"

      - name: Cache Gleam build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-gleam-build-${{ hashFiles('manifest.toml', 'gleam.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-build-

      - name: Install dependencies
        run: gleam deps download

      - name: Run test
        run: just test
